name: Build Nuxt (After Cypress Pass)

on:
  push:
    branches: [main] # หรือ pull_request, หรือตามต้องการ

jobs:
  cypress-tests:
    uses: titledev/demo-cypress/.github/workflows/cypress.yml@main
    secrets: inherit   # ✅ ส่ง secrets ไปด้วย

  build:
    runs-on: ubuntu-latest
    needs: cypress-tests   # ✅ รอ test ผ่านก่อน
    steps:
      - name: Checkout Nuxt repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt
        run: npm run build
