name: Build Nuxt (after test)

on:
  push:
    branches: [main]

jobs:
  run-tests:
    uses: titledev/demo-cypress/.github/workflows/cypress.yml@main
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
